-- Atelier seed: core rules + curated registry. Idempotent.
DELETE FROM rules WHERE source='core';
INSERT INTO rules (domain,key,value,source) VALUES
 ('code','file_word_budget','250 soft / 350 hard; exempt: md,json,yaml,lock,sql,generated','core'),
 ('code','dry','check graph/repo first; import, never rewrite; fix bugs in the shared function','core'),
 ('code','comments','sparse, intent-only; no narration; ponytail: notes for deliberate ceilings','core'),
 ('design','accent_budget','ONE brand accent, <=10% of any viewport','core'),
 ('design','accent_select','the accent is DATA, never a default: take it from project intake / logo / brand. If none is given, ASK once, or derive from the domain (fintech=blue, health=teal, luxury=gold, dev-tool=violet/orange). NEVER reflexively pick green/emerald - that is the AI-slop tell. Emerald is ONE example brand, not the house color','core'),
 ('design','theming','all colors as CSS variables in globals.css; semantic tokens in components; NEVER hardcode hex or per-page dark: overrides','core'),
 ('design','icons','Lucide 1.5px monochrome currentColor only; accent only on state','core'),
 ('design','motion','ease-out-expo entrances; springs 260/32/.9; stagger 60-80ms; reduced-motion fallback; transform/opacity only','core'),
 ('design','anti_style','no rainbow gradients, 3D emoji icons, colored icon circles, heavy shadows, bounce-ins, template grids','core'),
 ('structure','api_pattern','/api/v1/{feature}/{action}; thin endpoints, logic in services','core'),
 ('structure','monorepo','multiple frontends -> Turborepo apps/ + packages/','core'),
 ('auth','token_model','15min access JWT + 30day rotating single-use refresh; families; 60s grace; sliding window','core'),
 ('auth','refresh','silent one-shot timer + on-demand; single mutex per app; NEVER poll','core'),
 ('auth','redirect','login redirect is the LAST resort after silent refresh + session check','core'),
 ('stack','realtime','SSE or WebSockets, never polling; cache invalidation on write','core'),
 ('stack','llm_payloads','TOON over JSON for LLM-bound payloads; gRPC backend-to-backend','core'),
 ('stack','video_gen','Omni = gemini-omni-flash-preview, Google text->video (Veo 3.1 = fallback family). RUN mcp/assets/video.py generate(); do not hand-roll REST. Ladder: GOOGLE_API_KEY -> Vertex creds -> paste-prompt -> user mp4; rung 3 is SUCCESS, never exit on missing token','core'),
 ('stack','capability_search','before concluding Atelier cannot do something, grep skills/ AND commands/ AND mcp/ - not just agents/. A missing agent name is NOT missing capability: searching only for an agent produced "Atelier has no video" while asset-pipeline shipped it, and sent the agent to a heavier tool','core'),
 ('stack','media_verify','MEASURE generated media, never eyeball or assert: python mcp/assets/verify.py <file> [#accent] [--audio]. Audio present != audible (silence reads -91dB/-inf with a real AAC stream). Prompt saying "one accent" != obeying it (first Veo pass read 90% emerald vs the 10% cap). Report the number, not an adjective','core'),
 ('stack','omni_api','Omni interactions API exact shape: POST v1beta1/projects/{p}/locations/global/interactions, header Api-Revision: 2026-05-20 (REQUIRED - omitting it fails), body input=[{type:user_input,content:[{type:text,text:...}]}] (NOT a flat text part - the flat form in some docs is wrong). Response video arrives as inline base64 data OR a gs:// uri - handle BOTH or GCS-delivered successes silently look like failures','core'),
 ('stack','omni_first','prefer Omni (faster/cheaper) then Veo, but never trust its output blind: check the file is playable (non-empty + decodable stream) and, when audio was requested, actually audible - fall through to Veo if not. Whether Omni emits audio is contradicted across Google docs, so MEASURE, do not hardcode either belief','core'),
 ('stack','media_models','Veo IDs: veo-3.1-generate-001 is GA and the correct primary target; veo-3.1-generate-PREVIEW is a different, experimental id that 404s on most projects (mistaking it for "3.1 unavailable" is why builds fell back to 3.0); veo-3.0-generate-001 was slated for discontinuation 2026-06-30 - last-resort only. Ladder 3.1-001 -> 3.1-fast-preview -> 3.0-001 and REPORT which served. Omni Flash = silent video only via the v1beta1 interactions endpoint, NOT predictLongRunning','core'),
 ('code','commit_messages','pass commit bodies via -F file or -F -; inline -m with heredocs corrupts subjects (stray @). NEVER amend or force-push an already-pushed commit - that caused a branch divergence someone had to repair; fix forward with a new commit','core'),
 ('stack','video_audio','Veo 3+ generates SYNCED AUDIO natively - it is the headline feature over Veo 2. Silence is opt-IN: pass generateAudio in parameters AND describe the soundscape in the prompt (the prompt alone does nothing). Default audio=False suits scroll-scrubbed scrollytelling only; for hero/social/demo video ASK the user, never inherit silence from the scrollytelling recipe','core'),
 ('stack','video_creds','an expired/invalid GOOGLE_API_KEY must fall THROUGH to the next rung, never crash; probe by generating, not by GETting model metadata (metadata 404s on models that work)','core'),
 ('design','logo_gen','same credential ladder with Gemini image models; no key -> universal fill-in prompt for any platform; marks obey design-law (flat, hairline, one accent, 16px-crisp, light+dark variants)','core'),
 ('stack','image_gen','pick by job: gemini-3.1-flash-lite-image (Nano Banana 2 Lite, sub-2s/cheapest) for bulk drafts+storyboards; gemini-3.1-flash-image default finals; gemini-3-pro-image complex heroes only; 2.5-flash-image is legacy','core'),
 ('stack','credentials','project .env (gitignored), standard var names GOOGLE_API_KEY | GOOGLE_APPLICATION_CREDENTIALS+GOOGLE_CLOUD_PROJECT+GOOGLE_CLOUD_LOCATION; never in db or commits','core'),
 ('stack','assets','every raster -> webp via assets.py before serving; video -> frames -> webp for scrollytelling','core'),
 ('security','inputs','validate every external input at trust boundaries; parameterized queries only','core'),
 ('security','authz','ownership check on every endpoint; IDs from token never request body','core'),
 ('security','secrets','env/secret-manager only; never in code, logs, errors, or client bundle','core'),
 ('security','abuse_check','before shipping user-facing surface ask: how would I abuse this? rate-limit + Turnstile on public forms','core'),
 ('code','decisiveness','when asked to choose, choose ONE with a reason; hedge only on irreversible/safety calls','core'),
 ('code','debugging','reproduce first; read the actual error; root cause via graph callers; fix in shared path; leave a regression check; never claim fixed without running','core');

-- heal any pre-0.2.2 duplicates, then make them impossible: core rows upsert by (kind,name)
DELETE FROM registry WHERE id NOT IN (SELECT MIN(id) FROM registry GROUP BY kind,name);
CREATE UNIQUE INDEX IF NOT EXISTS registry_kind_name ON registry(kind,name);
INSERT OR REPLACE INTO registry (kind,name,source,install,usage,meta) VALUES
 ('component','shadcn/ui','https://ui.shadcn.com','MCP bundled with atelier / npx shadcn add','Radix primitives; restyle to tokens','a11y,ssr,dark,bundled-mcp'),
 ('component','Aceternity UI','https://ui.aceternity.com','MCP bundled with atelier / npx aceternity-ui add','premium animated sections; strip to one accent','animated,dark,bundled-mcp'),
 ('component','ReactBits','https://reactbits.dev','MCP bundled with atelier (GITHUB_TOKEN optional, lifts rate limit)','micro-interaction components','animated,bundled-mcp'),
 ('component','Motion.dev','https://motion.dev','npm i motion','springs, layout morphs; AI Kit (MCP+skills, 400+ examples) exists but needs a paid Motion+ token - do NOT bundle it; free docs at motion.dev/llms.txt','animated'),
 ('component','MagicUI','https://magicui.design','MCP bundled with atelier / npx magicui-cli add','marketing components; token restyle required','animated,dark,bundled-mcp'),
 ('skill','ponytail','github:ponytail','/plugin install ponytail','minimalism enforcement on every coding task',''),
 ('skill','ui-ux-pro-max','local skill','installed','style/palette/font intelligence for UI work',''),
 ('mcp','code-review-graph','local','code-review-graph build','structural graph: impact radius, callers, tests-for',''),
 ('mcp','stitch','MCP','installed','high-fidelity screen generation + design systems',''),
 ('component','Cult UI','https://cult-ui.com','npx cult-ui add','shadcn-ecosystem components with tasteful motion (dialogs/tabs/buttons)','animated,shadcn'),
 ('component','Kokonut UI','https://kokonutui.com','add @kokonutui to components.json (https://kokonutui.com/r/{name}.json), then npx shadcn@latest add @kokonutui/<name> — reachable via the bundled shadcn MCP','shadcn-ecosystem motion components for app UI','animated,shadcn,bundled-mcp'),
 ('component','Motion Primitives','https://motion-primitives.com','npm i motion','low-level composable Framer Motion blocks for custom effects','animated'),
 ('component','Bklit UI','https://bklit.com','add @bklit to components.json, then npx shadcn@latest add @bklit/<chart> — reachable via bundled shadcn MCP; project skill: npx skills add bklit/bklit-ui','15 composable charts on shadcn (area/line/candlestick/gauge/radar/sankey/heatmap); theme via chartCssVars + --chart-1..5','charts,dataviz,shadcn,bundled-mcp'),
 ('component','Anime.js v4','https://animejs.com','npm i animejs','fast tree-shakeable JS animation: createTimeline, stagger, SVG morphTo/createDrawable, createDraggable, onScroll, splitText, createSpring — see anime-js skill','animated'),
 ('tool','magicui-cli','https://magicui.design','npx magicui-cli add <component>','fetch MagicUI components via CLI (no MCP needed)',''),
 ('tool','aceternity-cli','https://ui.aceternity.com','npx aceternity-ui@latest add <component>','fetch Aceternity components via CLI',''),
 ('tool','github-mcp','npm:@modelcontextprotocol/server-github','npx -y @modelcontextprotocol/server-github (needs PAT)','read any component library source from its repo — no hallucination',''),
 ('site','Iconoir','https://iconoir.com','npm i iconoir-react','1600+ free SVG icons; React/RN/CSS native','icons,free'),
 ('site','Phosphor Icons','https://phosphoricons.com','npm i @phosphor-icons/react','6 weights per icon; thin/light match design-law stroke discipline','icons,free'),
 ('site','Heroicons','https://heroicons.com','npm i @heroicons/react','Tailwind-native icon set','icons,free'),
 ('site','3dicons','https://3dicons.co','download png/gltf','1500+ free open-source 3D icons; color/angle editable in browser','3d,free'),
 ('site','Shapefest','https://shapefest.com','download png','free high-res 3D shapes/hands/letters (clay, glass, metal)','3d,free'),
 ('site','IconScout 3D','https://iconscout.com/3d-illustrations','download gltf','large 3D asset library, free tier, built-in glTF editor','3d,freemium'),
 ('site','Astro Starlight','https://starlight.astro.build','npm i astro @astrojs/starlight','docs-site framework: sidebar, search, dark/light built in; restyle via --sl-color vars','docs,free'),
 ('component','Spline','https://spline.design','npm i @splinetool/react-spline @splinetool/runtime','design 3D scenes visually, embed + control via runtime (findObjectByName/emitEvent); no public API — ignore Spline MCP servers','3d,freemium'),
 ('component','React Three Fiber','https://r3f.docs.pmnd.rs','npm i three @react-three/fiber @react-three/drei','React renderer for three.js; drei helpers; dpr clamp + frameloop=demand','3d,free'),
 ('component','Threlte','https://threlte.xyz','npm i three @threlte/core @threlte/extras','Svelte renderer for three.js; extras mirror drei','3d,free'),
 ('component','Theatre.js','https://www.theatrejs.com','npm i @theatre/core @theatre/studio','keyframe/scroll-driven 3D sequencing; studio is DEV ONLY; @theatre/r3f bridge','3d,animated,free'),
 ('site','PeachWeb','https://peachweb.io','visual builder, exports embeds','no-code 3D website builder (WebGL); for clients who want 3D without code','3d,paid'),
 ('tool','threejs-devtools-mcp','npm:threejs-devtools-mcp','claude mcp add threejs-devtools-mcp -- npx threejs-devtools-mcp','inspect/edit a running three.js scene from the agent (59 tools); needs dev server up','3d,mcp');

DELETE FROM framework_map;
INSERT INTO framework_map (path,kind,purpose,load_when,links) VALUES
 ('skills/principal-mind/SKILL.md','skill','the thinking protocol: decisive answers, root-cause debugging, security reflexes, outcome-first reporting','FIRST, on every prompt — step 0 before all other skills; any bug/debug/security/decision task','loop-engine'),
 ('skills/loop-engine/SKILL.md','skill','the operating loop, model routing table, clarification protocol, termination rule','any nontrivial task; deciding which model tier; when to stop or ask','architect,builder,summarizer,principal-mind'),
 ('skills/design-law/SKILL.md','skill','premium UI law: vocabulary, tokens, motion, icons, component canon, anti-slop, checklist','any UI/design/landing/component/animation work','gateway,asset-pipeline,registry'),
 ('skills/clean-code-law/SKILL.md','skill','250-word file budget, DRY via graph, comment policy, split strategies','writing or refactoring any source code','file_size_gate'),
 ('skills/structure-law/SKILL.md','skill','canonical file trees per stack + intake questions','scaffolding, moving files, new projects','nextjs,fastapi'),
 ('skills/auth-law/SKILL.md','skill','token rotation/families/grace, silent refresh, anti-patterns, shipping checklist','ANY authentication/session work','deploy-advisor'),
 ('skills/deploy-advisor/SKILL.md','skill','hosting matrix with real costs; decision rules','choosing hosting, estimating costs, CI/CD setup',''),
 ('skills/gateway/SKILL.md','skill','resolves authoritative design files (core + overlays)','START of any UI task, before design-law','design-law,learner'),
 ('skills/asset-pipeline/SKILL.md','skill','webp/frames tools, scrollytelling recipe, video/logo generation credential ladder + universal prompts','images, video, logo/brand-mark generation, media, storytelling sections','assets.py,ScrollScrub,design-law'),
 ('skills/living-graphics/SKILL.md','skill','continuous component animations: SVG flow schematics, traveling packets, pulsing nodes, state-reactive micro-experiences, Rive/Lottie option','animated cards, data-flow diagrams, dynamic infographics, ambient/continuous/loop animation, micro-interactions','design-law,asset-pipeline'),
 ('skills/docs-site/SKILL.md','skill','Astro Starlight docs-site recipe: separate repo, base path, token restyle, MDX vs md, Pages deploy workflow','documentation site, docs, knowledge base, developer guides, MDX','design-law,deploy-advisor'),
 ('skills/web-3d/SKILL.md','skill','live 3D: Spline embed recipe, R3F/Threlte/three.js ladder, Theatre.js sequencing, 3D icons, performance laws, poster fallbacks','ANY 3D work — 3D hero, 3D icons, product viewer, WebGL, Spline, scroll-driven 3D','design-law,asset-pipeline,registry'),
 ('skills/stack-guides/nextjs.md','skill','Next.js decision rules + 5 agent mistakes','frontend work in Next.js','structure-law,design-law'),
 ('skills/stack-guides/fastapi.md','skill','FastAPI decision rules + 5 agent mistakes','Python backend/AI service work','structure-law'),
 ('skills/stack-guides/comms.md','skill','REST vs GraphQL vs gRPC vs SSE/WS vs TOON decision table','choosing protocols, streaming, real-time, API design','fastapi,redis-celery'),
 ('skills/stack-guides/redis-celery.md','skill','cache-aside + invalidation-on-write, idempotent background jobs, SSE progress','caching, background jobs, queues, stale-data bugs','comms'),
 ('skills/stack-guides/rag.md','skill','RAG ladder: context-first, hybrid+rerank pipeline, PageIndex trees, ADK rule','retrieval, embeddings, document QA, agent frameworks','fastapi'),
 ('skills/mcp-maker/SKILL.md','skill','ladder for integrating any site/library: registry row -> skill -> MCP server','adding a new component site, library, or API to Atelier','registry'),
 ('skills/anime-js/SKILL.md','skill','Anime.js v4 API: animate/createTimeline/stagger, SVG morph+draw, draggable, onScroll, splitText, springs, React scope','JS animation not covered by Framer Motion: timelines, SVG morph/draw, draggable, motion paths, text splitting','design-law,living-graphics,registry'),
 ('agents/architect.md','agent','Opus planner: architecture + done-state contracts, never codes','/atelier:plan; architectural holes during build','loop-engine'),
 ('agents/builder.md','agent','Sonnet executor: implements plan tasks under all laws','/atelier:build task execution','loop-engine,clean-code-law'),
 ('agents/summarizer.md','agent','Haiku: digests, store updates, trivial edits','summaries, memory persistence, mechanical edits',''),
 ('agents/learner.md','agent','Sonnet ingester: references -> overlays + registry rows, never touches core','/atelier:learn ingestion','gateway'),
 ('agents/design-scout.md','agent','parallel scout: studies premium component source (Aceternity/ReactBits/MagicUI) and returns technique briefs + durable rules','spawn alongside any UI build/plan task','design-law,registry,builder'),
 ('db/store.py','tool','SQLite CLI: init/rules/registry/map/sql/exec, TOON-style pipe rows','reading rules, plans, criteria, registry, this map',''),
 ('mcp/assets/assets.py','tool','image->webp, video->webp frames','optimizing any raster; scrollytelling frames','asset-pipeline'),
 ('hooks/file_size_gate.py','tool','enforces 250/350-word file law on every write','automatic (PostToolUse hook)','clean-code-law'),
 ('hooks/session_start.py','tool','resumes active plan + unmet criteria on session start','automatic (SessionStart hook)','loop-engine'),
 ('templates/ScrollScrub.tsx','template','canvas scroll-scrubbed frame sequence component','building scrollytelling sections','asset-pipeline'),
 ('docs/REQUIREMENTS.md','doc','full product spec: what Atelier is and why','understanding scope; contributor onboarding',''),
 ('docs/IMPLEMENTATION-PLAN.md','doc','architecture, schema, phased build plan with gates','planning framework changes; contributor onboarding','');
